# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [40]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import time
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [41]:
city_dictionary= pd.read_csv('./city_data.csv')
city_dictionary

,Unnamed: 0,Country,Cloudiness,Humidity,Date,Latitude,Longitude,Max Temp,Wind Speed,City
0,0,PF,1,71,1616429119,-23.1203,-134.9692,26.57,3.23,rikitea
1,1,MX,1,55,1616429165,27.9769,-114.0611,15.50,4.93,guerrero negro
2,2,CK,75,89,1616429188,-21.2078,-159.7750,26.00,2.06,avarua
3,3,CA,40,75,1616428677,65.2820,-126.8329,-33.00,0.47,norman wells
4,4,US,90,100,1616429191,37.0431,-100.9210,6.00,5.14,liberal
...,...,...,...,...,...,...,...,...,...,...
553,553,GW,58,50,1616429996,11.2833,-15.8333,25.34,4.91,bubaque
554,554,AU,90,94,1616429715,-21.1500,149.2000,25.00,0.51,mackay
555,555,CG,40,66,1616429999,-4.7561,11.8578,30.00,3.70,loandjili
556,556,SV,0,44,1616429834,13.5928,-89.8275,28.00,1.54,acajutla
557,557,CL,0,50,1616430001,-20.2208,-70.1431,24.00,8.75,iquique

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [42]:
#Configure gmaps
gmaps.configure(api_key=g_key)

#Store locations
locations= city_dictionary[['Latitude', 'Longitude']]

#Store Humidity
Humidity = city_dictionary['Humidity']

# Plot Heatmap
figure = gmaps.figure(center = (46.0, -5.0), zoom_level = 2)
maximum_intensity = np.max(Humidity)
#Create heat layer
hot_ass_layer = gmaps.heatmap_layer(locations, weights = 
                                    Humidity, dissipating=False,
                                    max_intensity=100, point_radius=3)

#Add layer
figure.add_layer(hot_ass_layer)

print(figure)

Figure(layout=FigureLayout(height='420px'))

In [43]:
maximum_intensity

100

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [44]:
#Narrow Cities that fit conditions
narrow_df =  city_dictionary.loc[(city_dictionary["Wind Speed"] <= 10) & (city_dictionary["Cloudiness"] == 0) & \
                            (city_dictionary["Max Temp"] >= 16) & (city_dictionary["Max Temp"] <= 27)].dropna()

narrow_df

,Unnamed: 0,Country,Cloudiness,Humidity,Date,Latitude,Longitude,Max Temp,Wind Speed,City
28,28,CL,0,56,1616429174,-29.9533,-71.3436,20.00,6.69,coquimbo
38,38,ZA,0,64,1616429101,-33.9180,25.5701,21.00,4.12,port elizabeth
42,42,ZA,0,66,1616429241,-34.4187,19.2345,22.22,4.92,hermanus
49,49,AU,0,79,1616429250,-34.7333,135.8667,19.22,1.93,port lincoln
55,55,ZA,0,44,1616429000,-33.9258,18.4232,27.00,6.69,cape town
63,63,SA,0,52,1616429270,18.2164,42.5053,24.00,3.09,abha
79,79,ZA,0,53,1616429293,-34.5322,20.0403,23.00,8.23,bredasdorp
95,95,PE,0,54,1616429102,-13.7000,-76.2167,27.00,9.26,pisco
111,111,IN,0,76,1616429336,14.9167,79.9833,25.35,3.45,kavali
132,132,AU,0,78,1616429405,-24.8667,113.6333,25.00,9.26,carnarvon
133,133,CL,0,57,1616429407,-35.3333,-72.4167,20.23,3.07,constitucion
139,139,AU,0,91,1616429415,-38.2667,141.9667,16.30,3.25,codrington
182,182,OM,0,26,1616429478,22.9333,57.5333,24.84,4.90,nizwa
195,195,CV,0,72,1616429498,14.8961,-24.4956,21.81,5.38,sao filipe
221,221,EG,0,27,1616429536,31.3525,27.2453,23.00,5.14,marsa matruh
224,224,ES,0,54,1616429540,42.7762,-9.0603,20.56,1.66,muros
282,282,IR,0,13,1616429624,31.6128,55.4107,20.30,0.55,bafq
337,337,ES,0,58,1616429700,43.2686,-7.5406,16.11,4.92,bereda
373,373,MX,0,12,1616429750,21.0167,-102.1667,20.79,3.23,san julian
376,376,ZA,0,68,1616429754,-34.0033,24.7314,20.00,2.24,kruisfontein
406,406,ZA,0,76,1616429796,-34.0527,23.3716,18.50,6.69,plettenberg bay
413,413,IN,0,70,1616429805,16.9833,73.3000,26.45,4.05,ratnagiri
427,427,AR,0,24,1616429824,-43.3002,-65.1023,26.81,4.86,rawson
484,484,IN,0,40,1616429904,27.0167,95.5667,19.03,1.97,khonsa
494,494,AR,0,35,1616429917,-45.8667,-67.5000,23.00,4.12,comodoro rivadavia
508,508,MM,0,33,1616429935,25.3833,97.4000,23.95,1.13,myitkyina
520,520,IR,0,11,1616429951,30.4067,55.9939,18.14,1.10,rafsanjan
524,524,PK,0,77,1616429957,25.1216,62.3254,24.27,6.76,gwadar
557,557,CL,0,50,1616430001,-20.2208,-70.1431,24.00,8.75,iquique

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [45]:
hotel_df = narrow_df.loc[:, ['City','Country','Latitude', 'Longitude']]
#add Hotel name column
hotel_df['Hotel Name'] =''

#Display the result

hotel_df

                   City Country  Latitude  Longitude Hotel Name
28             coquimbo      CL  -29.9533   -71.3436
38       port elizabeth      ZA  -33.9180    25.5701
42             hermanus      ZA  -34.4187    19.2345
49         port lincoln      AU  -34.7333   135.8667
55            cape town      ZA  -33.9258    18.4232
63                 abha      SA   18.2164    42.5053
79           bredasdorp      ZA  -34.5322    20.0403
95                pisco      PE  -13.7000   -76.2167
111              kavali      IN   14.9167    79.9833
132           carnarvon      AU  -24.8667   113.6333
133        constitucion      CL  -35.3333   -72.4167
139          codrington      AU  -38.2667   141.9667
182               nizwa      OM   22.9333    57.5333
195          sao filipe      CV   14.8961   -24.4956
221        marsa matruh      EG   31.3525    27.2453
224               muros      ES   42.7762    -9.0603
282                bafq      IR   31.6128    55.4107
337              bereda      ES   43.2686    -7.5406
373          san julian      MX   21.0167  -102.1667
376        kruisfontein      ZA  -34.0033    24.7314
406     plettenberg bay      ZA  -34.0527    23.3716
413           ratnagiri      IN   16.9833    73.3000
427              rawson      AR  -43.3002   -65.1023
484              khonsa      IN   27.0167    95.5667
494  comodoro rivadavia      AR  -45.8667   -67.5000
508           myitkyina      MM   25.3833    97.4000
520           rafsanjan      IR   30.4067    55.9939
524              gwadar      PK   25.1216    62.3254
557             iquique      CL  -20.2208   -70.1431

In [56]:
base_url ="https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {'type' : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

for index, row in hotel_df.iterrows():
    #get city name, latitude, lng form dataframe
    latitude =row['Latitude']
    longitude = row ['Longitude']
    city_name = row ['City']
    
    #add keyword to dictionary
    params['location'] = f'{latitude}, {longitude}'
    
    #assemble url and make API request
    print(f'Retrieving Result for Index {index}: {city_name}.')
    response = requests.get(base_url, params=params).json()
    #extract results
    results = response ['results']
    
    #save the hotel name to dataframe
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
    #except no hotel
    except (KeyError, IndexError):
        print('No Hotel....skipping')
        print('-------------')
        
    #Wait 1 sec to make another apit request to avoid SSL Error
    time.sleep(1)
#Print end of search once searching is completed
print ('------End of Search-----')

Retrieving Result for Index 28: coquimbo.
No Hotel....skipping
-------------
Retrieving Result for Index 38: port elizabeth.
No Hotel....skipping
-------------
Retrieving Result for Index 42: hermanus.
No Hotel....skipping
-------------
Retrieving Result for Index 49: port lincoln.
No Hotel....skipping
-------------
Retrieving Result for Index 55: cape town.
No Hotel....skipping
-------------
Retrieving Result for Index 63: abha.
No Hotel....skipping
-------------
Retrieving Result for Index 79: bredasdorp.
No Hotel....skipping
-------------
Retrieving Result for Index 95: pisco.
No Hotel....skipping
-------------
Retrieving Result for Index 111: kavali.
No Hotel....skipping
-------------
Retrieving Result for Index 132: carnarvon.
No Hotel....skipping
-------------
Retrieving Result for Index 133: constitucion.
No Hotel....skipping
-------------
Retrieving Result for Index 139: codrington.
No Hotel....skipping
-------------
Retrieving Result for Index 182: nizwa.
No Hotel....skipping
-------------
Retrieving Result for Index 195: sao filipe.
No Hotel....skipping
-------------
Retrieving Result for Index 221: marsa matruh.
No Hotel....skipping
-------------
Retrieving Result for Index 224: muros.
No Hotel....skipping
-------------
Retrieving Result for Index 282: bafq.
No Hotel....skipping
-------------
Retrieving Result for Index 337: bereda.
No Hotel....skipping
-------------
Retrieving Result for Index 373: san julian.
No Hotel....skipping
-------------
Retrieving Result for Index 376: kruisfontein.
No Hotel....skipping
-------------
Retrieving Result for Index 406: plettenberg bay.
No Hotel....skipping
-------------
Retrieving Result for Index 413: ratnagiri.
No Hotel....skipping
-------------
Retrieving Result for Index 427: rawson.
No Hotel....skipping
-------------
Retrieving Result for Index 484: khonsa.
No Hotel....skipping
-------------
Retrieving Result for Index 494: comodoro rivadavia.
No Hotel....skipping
-------------
Retrieving Result for Index 508: myitkyina.
No Hotel....skipping
-------------
Retrieving Result for Index 520: rafsanjan.
No Hotel....skipping
-------------
Retrieving Result for Index 524: gwadar.
No Hotel....skipping
-------------
Retrieving Result for Index 557: iquique.
No Hotel....skipping
-------------
------End of Search-----

In [57]:
#Disply hotel df
hotel_df

                   City Country  Latitude  Longitude Hotel Name
28             coquimbo      CL  -29.9533   -71.3436
38       port elizabeth      ZA  -33.9180    25.5701
42             hermanus      ZA  -34.4187    19.2345
49         port lincoln      AU  -34.7333   135.8667
55            cape town      ZA  -33.9258    18.4232
63                 abha      SA   18.2164    42.5053
79           bredasdorp      ZA  -34.5322    20.0403
95                pisco      PE  -13.7000   -76.2167
111              kavali      IN   14.9167    79.9833
132           carnarvon      AU  -24.8667   113.6333
133        constitucion      CL  -35.3333   -72.4167
139          codrington      AU  -38.2667   141.9667
182               nizwa      OM   22.9333    57.5333
195          sao filipe      CV   14.8961   -24.4956
221        marsa matruh      EG   31.3525    27.2453
224               muros      ES   42.7762    -9.0603
282                bafq      IR   31.6128    55.4107
337              bereda      ES   43.2686    -7.5406
373          san julian      MX   21.0167  -102.1667
376        kruisfontein      ZA  -34.0033    24.7314
406     plettenberg bay      ZA  -34.0527    23.3716
413           ratnagiri      IN   16.9833    73.3000
427              rawson      AR  -43.3002   -65.1023
484              khonsa      IN   27.0167    95.5667
494  comodoro rivadavia      AR  -45.8667   -67.5000
508           myitkyina      MM   25.3833    97.4000
520           rafsanjan      IR   30.4067    55.9939
524              gwadar      PK   25.1216    62.3254
557             iquique      CL  -20.2208   -70.1431

In [63]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [60]:
# Add marker layer ontop of heat map
markers =gmaps.marker_layer(locations, info_box_content = hotel_info)
figure.add_layer(markers)
# Display figure
figure

Figure(layout=FigureLayout(height='420px'))